#ifndef _INCLUDE_NXS_CHAT_SRV_U_DB_ISSUES_SUBUNITS_H
#define _INCLUDE_NXS_CHAT_SRV_U_DB_ISSUES_SUBUNITS_H

// clang-format off

/*%%_NXS_TPL_HEADERS_TYPEDEF_BEGIN_%%*/
/*%%_NXS_TPL_HEADERS_TYPEDEF_END_%%*/

/*%%_NXS_TPL_HEADERS_BEGIN_%%*/
/*%%_NXS_TPL_HEADERS_END_%%*/

#endif /* _INCLUDE_NXS_CHAT_SRV_U_DB_ISSUES_SUBUNITS_H */
