#ifndef _INCLUDE_NXS_CHAT_SRV_M_QUEUE_COM_H
#define _INCLUDE_NXS_CHAT_SRV_M_QUEUE_COM_H

// clang-format off

typedef enum
{
	NXS_CHAT_SRV_M_QUEUE_COM_TYPE_NONE,
	NXS_CHAT_SRV_M_QUEUE_COM_TYPE_TLGRM_UPDATE,
	NXS_CHAT_SRV_M_QUEUE_COM_TYPE_RDMN_UPDATE,
} nxs_chat_srv_m_queue_com_types_t;

#endif /* _INCLUDE_NXS_CHAT_SRV_M_QUEUE_COM_H */
