#!/bin/bash

P_NAME="nxs-chat-srv"

VER="0.3.1"
BUILD_VERSION="1"

GENERIC_DOCKER_IMG_DEBIAN_general=""
GENERIC_DOCKER_IMG_CENTOS_general=""

GENERIC_DOCKER_IMG_DEBIAN_7=""
GENERIC_DOCKER_IMG_DEBIAN_8=""
GENERIC_DOCKER_IMG_DEBIAN_9=""
GENERIC_DOCKER_IMG_CENTOS_6=""
GENERIC_DOCKER_IMG_CENTOS_7=""

RELEASE=""
command='build'
BUILD_TYPE="docker"
USE_CHOWN="false"
DEB_TAR_ORIG=""
BUILD_DIR=""
USE_OWN_IMAGE="false"

USER=`whoami`

HELP_MSG="Simple script to make packages for different OS releases.\n\
\n\
Options:\n\
        -r RELEASE     : make build for specified OS release (e.g. debian:9, centos:7, etc). You may use 'all' to make builds for all releases.\n\
        -c COMMAND     : 'build' and 'make-orig' commands are available.\n\
        -t BUILD_TYPE  : specify how to make your build ('docker' or 'local'). 'local' build would be useful for CI/CD process.\n\
        -b BUILD_DIR   : specify directory for build project. Useful for CI/CD process.\n\
        -C             : if specified, chown command with sudo for output files will be used after build process is finished\n\
        -d DEB_TAR_ORIG: use debian tar orig file to make package. It is useful if you make packages for debian:8 and debian:9 together.\n\
        -I             : use project own docker image
        -h             : show help message (this message).\n\
"

while getopts c:r:t:b:Cd:Ih option
do
	case "${option}" in
		r) RELEASE=${OPTARG};;
		c) command=${OPTARG};;
		t) BUILD_TYPE=${OPTARG};;
		b) BUILD_DIR=${OPTARG};;
		C) USE_CHOWN="true";;
		d) DEB_TAR_ORIG=${OPTARG};;
		I) USE_OWN_IMAGE="true";;
		h) echo -e ${HELP_MSG}; exit 0;;
	esac
done

if [ -z "${BUILD_DIR}" ];
then

	BUILD_DIR="/tmp/nxs-build/${P_NAME}"
else

	# Get absolute path for BUILD_DIR
	BUILD_DIR=$(mkdir -p ${BUILD_DIR} && cd ${BUILD_DIR} && pwd)
fi

function copy_source()
{
	local dst_package_dir="$1"
	
	# Coping source code into build environment
	rsync -qr \
		build-pkgs-conf/pkg \
		.nxs-fw-settings \
		docs \
		src \
		Makefile \
		config.mk \
		distrib.mk \
		LICENSE \
		README.md \
		${dst_package_dir}
}

function build_package_deb_local()
{
	local build_path="$1"
	local tpl_path="${build_path}/deb-tpl"
	
	(
		cd ${build_path}/${P_NAME}

		dh_make -p ${P_NAME}_${VER} --copyright lgpl3 --single --templates ${tpl_path} --yes --createorig

		dpkg-buildpackage
	)
}

function make_orig()
{

	local dst_root_dir="${BUILD_DIR}/orig"
	local dst_package_dir="${dst_root_dir}/${P_NAME}"

	# Preparing build environment
	rm -rf ${dst_root_dir} || exit 1
	mkdir -p ${dst_package_dir} || exit 1

	mkdir -p ${dst_package_dir}/objs || exit 1
	mkdir -p ${dst_package_dir}/pkg || exit 1

	copy_source ${dst_package_dir}

	tar zcf ${dst_root_dir}/${P_NAME}_${VER}.orig.tar.gz -C ${dst_package_dir} .
	tar Jcf ${dst_root_dir}/${P_NAME}_${VER}.orig.tar.xz -C ${dst_package_dir} .

	rm -rf ${dst_package_dir}
}

function build_package_deb()
{

	local gen_img_name
	local dc_name

	r=$1

	if [ "${r}" == "general" ];
	then

		bv="${BUILD_VERSION}"
	else

		bv="deb${r}u${BUILD_VERSION}"
	fi

	local deb_tar_orig_path="$2"

	local dst_root_dir="${BUILD_DIR}/debian-${r}"
	local dst_package_dir="${dst_root_dir}/${P_NAME}"
	local dst_install_file="${dst_root_dir}/deb-tpl/${P_NAME}.install"

	# Preparing docker image
	if [ "${BUILD_TYPE}" == "docker" ];
	then

		if [ "${USE_OWN_IMAGE}" == "true" ];
		then
		
			dc_name="nxs-build_${P_NAME}_debian:${r}"
			docker build -t ${dc_name} build-pkgs-conf/docker/debian-${r} || exit 1
		else
		
			gen_img_name="GENERIC_DOCKER_IMG_DEBIAN_${r}"
			dc_name="${!gen_img_name:-}"
		fi
	fi
	
	# Preparing build environment
	rm -rf ${dst_root_dir} || exit 1
	mkdir -p ${dst_package_dir} || exit 1
	
	if [ -z "${deb_tar_orig_path}" ];
	then
	
		mkdir -p ${dst_package_dir}/objs || exit 1
		mkdir -p ${dst_package_dir}/pkg || exit 1

		copy_source ${dst_package_dir}
	else
	
		cp ${deb_tar_orig_path} ${dst_root_dir}

		case ${r} in
			7)
				tar -zxf ${deb_tar_orig_path} -C ${dst_package_dir} || exit 1
				;;
			8|9|general)
				tar -pJxf ${deb_tar_orig_path} -C ${dst_package_dir} || exit 1
				;;
			*)
				echo "unknown Debian releasse number"
				exit 1
				;;
		esac
	fi

	# Docker build script
	rsync build-pkgs-conf/docker/deb-build.sh "${dst_root_dir}" || exit 1

	# Debian package template
	rsync -r build-pkgs-conf/tpls/debian-${r}/ ${dst_root_dir}/deb-tpl || exit 1
	sed -i 's/\$\$BUILD_VERSION\$\$/'${bv}'/g' ${dst_root_dir}/deb-tpl/changelog || exit 1

	if [ "${BUILD_TYPE}" == "docker" ];
	then
	
		# Docker build package
		docker run -it --rm -v "${dst_root_dir}:/tmp/build" -e "DEBEMAIL=$DEBEMAIL" -e "DEBFULLNAME=$DEBFULLNAME" ${dc_name} /tmp/build/deb-build.sh ${P_NAME} ${VER} || exit 1
	else
	
		build_package_deb_local "${dst_root_dir}" || exit 1
	fi
	
	# Change owner from root to current user
	if [ "${USE_CHOWN}" == "true" ];
	then
	
		sudo chown -R ${USER} ${dst_root_dir}
	fi

	# Remove junk
	rm -rf ${dst_package_dir} 2>/dev/null
	rm -rf ${dst_root_dir}/deb-tpl 2>/dev/null
	rm -rf ${dst_root_dir}/deb-build.sh 2>/dev/null

	return 0
}

function build_package_centos_local()
{
	local build_path="$1"

	(
		cd "${build_path}"
		
		tar zcfv ${P_NAME}-${VER}.tar.gz ${P_NAME}-${VER}
		
		rpmbuild --define "_rpmdir ${build_path}" --define "_srcrpmdir ${build_path}" --define "_sourcedir ${build_path}" --target=x86_64 -ba "${build_path}/${P_NAME}.spec"
		
		cp ${build_path}/x86_64/* ${build_path}/
		
		rm -rf ${build_path}/x86_64/
		
		rm ${P_NAME}-${VER}.tar.gz
	)
}

function build_package_centos()
{

	local gen_img_name
	local dc_name

	r=$1

	local headers=""
	local headers_dir=""
	local static_libs=""
	local desc=""
	local files=""
	
	local dst_root_dir="${BUILD_DIR}/centos-${r}"
	local dst_package_dir="${dst_root_dir}/${P_NAME}-${VER}"
	local dst_spec_file="${dst_root_dir}/${P_NAME}.spec"
	local dc_name="nxs-build_${P_NAME}_centos:${r}"

	# Preparing docker image
	if [ "${BUILD_TYPE}" == "docker" ];
	then

		if [ "${USE_OWN_IMAGE}" == "true" ];
		then
		
			dc_name="nxs-build_${P_NAME}_centos:${r}"
			docker build -t ${dc_name} build-pkgs-conf/docker/centos-${r} || exit 1
		else
		
			gen_img_name="GENERIC_DOCKER_IMG_CENTOS_${r}"
			dc_name="${!gen_img_name:-}"
		fi
	fi
	
	# Preparing build environment
	rm -rf "${dst_root_dir}" || exit 1
	mkdir -p "${dst_package_dir}" || exit 1
	mkdir -p "${dst_package_dir}/objs" || exit 1
	mkdir -p "${dst_package_dir}/pkg" || exit 1
	
	copy_source ${dst_package_dir}
	
	# Docker build script
	cp build-pkgs-conf/docker/rpm-build.sh "${dst_root_dir}" || exit 1

	# Centos spec file
	cp build-pkgs-conf/tpls/centos-${r}/${P_NAME}.spec ${dst_spec_file} || exit 1
	sed -i 's/\$\$BUILD_VERSION\$\$/'${BUILD_VERSION}'/g' ${dst_spec_file} || exit 1
	sed -i 's/\$\$VERSION\$\$/'${VER}'/g' ${dst_spec_file} || exit 1
	
	if [ "${BUILD_TYPE}" == "docker" ];
	then
	
		# Docker build package
		docker run -it --rm -v "${dst_root_dir}:/tmp/build" ${dc_name} /tmp/build/rpm-build.sh ${P_NAME} ${VER} || exit 1
	else
	
		build_package_centos_local "${dst_root_dir}" || exit 1
	fi
	
	# Change owner from root to current user
	if [ "${USE_CHOWN}" == "true" ];
	then
	
		sudo chown -R ${USER} "${dst_root_dir}"
	fi
	
	# Remove junk
	rm -rf "${dst_package_dir}" 2>/dev/null
	rm -rf "${dst_spec_file}" 2>/dev/null
	rm -rf "${dst_root_dir}/rpm-build.sh" 2>/dev/null
	
	return 0
}

function build_package()
{
	case ${RELEASE} in
		"debian:general" )
			build_package_deb general "${DEB_TAR_ORIG}"
			;;

		"centos:general" )
			build_package_centos general
			;;

		"debian:7" )
			build_package_deb 7 "${DEB_TAR_ORIG}"
			;;

		"debian:8" )
			build_package_deb 8 "${DEB_TAR_ORIG}"
			;;

		"debian:9" )
			build_package_deb 9 "${DEB_TAR_ORIG}"
			;;
			
		"centos:6" )
			build_package_centos 6
			;;

		"centos:7" )
			build_package_centos 7
			;;

		"all" )
			make_orig
			if [ $? -ne 0 ];
			then
				echo "can't make orig archives"
				exit 1
			fi

#			build_package_deb general "${BUILD_DIR}/orig/${P_NAME}_${VER}.orig.tar.xz"
#			if [ $? -ne 0 ];
#			then
#				echo "can't build package: debian:general"
#				exit 1
#			fi
#
#			build_package_centos general
#			if [ $? -ne 0 ];
#			then
#				echo "can't build package: centos:general"
#				exit 1
#			fi
#
#			build_package_deb 7 "${BUILD_DIR}/orig/${P_NAME}_${VER}.orig.tar.gz"
#			if [ $? -ne 0 ];
#			then
#				echo "can't build package: debian:7"
#				exit 1
#			fi

			build_package_deb 8 "${BUILD_DIR}/orig/${P_NAME}_${VER}.orig.tar.xz"
			if [ $? -ne 0 ];
			then
				echo "can't build package: debian:8"
				exit 1
			fi

			build_package_deb 9 "${BUILD_DIR}/orig/${P_NAME}_${VER}.orig.tar.xz"
			if [ $? -ne 0 ];
			then
				echo "can't build package: debian:9"
				exit 1
			fi

#			build_package_centos 6
#			if [ $? -ne 0 ];
#			then
#				echo "can't build package: centos:6"
#				exit 1
#			fi
			
			build_package_centos 7
			if [ $? -ne 0 ];
			then
				echo "can't build package: centos:7"
				exit 1
			fi
			;;

		*)
			echo "unknown release"
			;;
	esac
}

case $command in

	build)

		if [ -z "${RELEASE}" ];
		then

			echo -n "Input OS (e.g. debian:9): "
			read RELEASE
		fi

		if [ ! "${BUILD_TYPE}" == "docker" ] && [ ! "${BUILD_TYPE}" == "local" ];
		then

			echo "Wrong build type. Only 'docker' or 'local' types are available."
			exit 1
		fi

		build_package
		;;

	make-orig)

		make_orig
		;;

	*)

		echo "Unknown command: $command"
		;;
esac
