#ifndef _INCLUDE_NXS_CHAT_SRV_P_QUEUE_WORKER_SUBPROC_H
#define _INCLUDE_NXS_CHAT_SRV_P_QUEUE_WORKER_SUBPROC_H

// clang-format off

/*%%_NXS_TPL_HEADERS_BEGIN_%%*/
/*%%_NXS_TPL_HEADERS_END_%%*/

#endif /* _INCLUDE_NXS_CHAT_SRV_P_QUEUE_WORKER_SUBPROC_H */
