#ifndef _INCLUDE_NXS_CHAT_SRV_U_TLGRM_ANSWERCALLBACKQUERY_TYPEDEF_H
#define _INCLUDE_NXS_CHAT_SRV_U_TLGRM_ANSWERCALLBACKQUERY_TYPEDEF_H

// clang-format off



#endif /* _INCLUDE_NXS_CHAT_SRV_U_TLGRM_ANSWERCALLBACKQUERY_TYPEDEF_H */
