#ifndef _INCLUDE_NXS_CHAT_SRV_D_RDMN_LAST_ISSUE_TYPEDEF_H
#define _INCLUDE_NXS_CHAT_SRV_D_RDMN_LAST_ISSUE_TYPEDEF_H

// clang-format off



#endif /* _INCLUDE_NXS_CHAT_SRV_D_RDMN_LAST_ISSUE_TYPEDEF_H */
