#ifndef _INCLUDE_NXS_CHAT_SRV_P_QUEUE_WORKER_TLGRM_UPDATE_WIN_ADDED_TO_ISSUE_CTX_H
#define _INCLUDE_NXS_CHAT_SRV_P_QUEUE_WORKER_TLGRM_UPDATE_WIN_ADDED_TO_ISSUE_CTX_H

// clang-format off

typedef struct
{

} nxs_chat_srv_p_queue_worker_tlgrm_update_win_added_to_issue_ctx_t;

void						nxs_chat_srv_p_queue_worker_tlgrm_update_win_added_to_issue_ctx_init				(nxs_chat_srv_p_queue_worker_tlgrm_update_win_added_to_issue_ctx_t *p_ctx);
void						nxs_chat_srv_p_queue_worker_tlgrm_update_win_added_to_issue_ctx_free				(nxs_chat_srv_p_queue_worker_tlgrm_update_win_added_to_issue_ctx_t *p_ctx);

#endif /* _INCLUDE_NXS_CHAT_SRV_P_QUEUE_WORKER_TLGRM_UPDATE_WIN_ADDED_TO_ISSUE_CTX_H */
