#ifndef _INCLUDE_NXS_CHAT_SRV_P_QUEUE_WORKER_RDMN_UPDATE_WIN_ISSUE_UPDATED_CTX_H
#define _INCLUDE_NXS_CHAT_SRV_P_QUEUE_WORKER_RDMN_UPDATE_WIN_ISSUE_UPDATED_CTX_H

// clang-format off

typedef struct
{

} nxs_chat_srv_p_queue_worker_rdmn_update_win_issue_updated_ctx_t;

void						nxs_chat_srv_p_queue_worker_rdmn_update_win_issue_updated_ctx_init				(nxs_chat_srv_p_queue_worker_rdmn_update_win_issue_updated_ctx_t *p_ctx);
void						nxs_chat_srv_p_queue_worker_rdmn_update_win_issue_updated_ctx_free				(nxs_chat_srv_p_queue_worker_rdmn_update_win_issue_updated_ctx_t *p_ctx);

#endif /* _INCLUDE_NXS_CHAT_SRV_P_QUEUE_WORKER_RDMN_UPDATE_WIN_ISSUE_UPDATED_CTX_H */
